apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runner-cluster-reader
rules:
- apiGroups: [ "" ]
  resources: [ "nodes", "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "metrics.k8s.io" ]
  resources: [ "nodes" ]
  verbs: [ "get", "list", "watch" ]
