name: "Runner Scaling Test"
on: workflow_dispatch # Allows manual triggering

jobs:
  run-on-self-hosted:
    runs-on: ["self-hosted", "linux"]
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # 10 parallel jobs
    steps:
      - name: Print runner details
        run: |
          echo "Running on GitHub Runner"
          echo "Hostname: $(hostname)"
          sleep 60
