name: "Runner Scaling Test"
on: workflow_dispatch

jobs:
  run-on-self-hosted:
    runs-on: arc-runner-set
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Print runner details
        run: |
          echo "Running on GitHub Runner"
          echo "Hostname: $(hostname)"
          sleep 60
